name: CytonicBedWars
version: '${version}'
description: 'stuff'
authors:
  - Foxikle
  - Webhead1104
main: net.cytonic.cytonicbedwars.CytonicBedWars
api-version: '1.20'
depend:
  - CustomNPCs
  - SlimeWorldManager
commands:
  debug:
    description: Debugging command :)
  item:
    description: A command to give you items
    aliases:
      - i
  openitemshop:
    description: Opens the item shop
  openteamshop:
    description: Opens the team shop
permissions:
  cytonic.bedwars.*:
    default: op
    description: A wildcard permission
    children:
      - cytonic.bedwars.item_command
      - cytonic.bedwars.debug
  cytonic.bedwars.item_command:
    description: A permission to use the /item command
    default: op
  cytonic.bedwars.debug:
    description: A permission to use the /debug command
